### ISSUE TITLE
ProposalCard incorrectly assumes all units are in wei

### ISSUE THREAD

**Issue by ztnark** [odyssy-automaton/pokemol-web#1064]
https://github.com/HausDAO/pokemol-web/blob/develop/src/components/proposalCard.jsx#L207

This leads to display issues for tokens that are not denominated in wei, such as USDT on Polygon:

![image](https://user-images.githubusercontent.com/4923997/116563007-a8e2d000-a8d1-11eb-8475-b719940653a2.png)

**Comment by jordanlesich** [comment]
Thanks for bringing this up. We'll take a look into it,

**Comment by jordanlesich** [comment]
This should be fixed.

**Comment by ztnark** [comment]
It is! Thank you for the quick turnaround 🙏
