### ISSUE TITLE
Format/navigation error on mobile Dapp in MetaMask Browser

### ISSUE THREAD

**Issue by skyminelabs** [odyssy-automaton/pokemol-web#1262]
Using mobile Dapp from within iOS MetaMask, I have trouble using "Filter By".

I am not able to easily choose "Active" or "All".  I am able to choose the choices lower down.  But the top ones are getting mixed with what is behind it.  The "Sort By" tool.  

Screenshot attached:
![image](https://user-images.githubusercontent.com/57817726/127481603-49da316c-adb5-498f-a610-23d79a8ad2c9.png)

I also have a video to show if easier.

**Comment by skuhlmann** [comment]
Fixed.
