### ISSUE TITLE
Update Heading for Signal Proposal Types

### ISSUE THREAD

**Issue by earth2travis** [odyssy-automaton/pokemol-web#1279]
This is a bug fix

## Expected Behavior

**WHEN** a Signal proposal is submitted
**THEN** the proposal card / details should show "Signal Proposal"

## Actual Behavior

**WHEN** a Signal proposal is submitted
**THEN** the proposal card / details shows "Funding Proposal"

**Proposal Card**
![image](https://user-images.githubusercontent.com/522182/129078863-879e596c-ffa3-4303-998a-3f14cb0b0efb.png)

**Proposal Details**
![image](https://user-images.githubusercontent.com/522182/129078464-85b25fbb-9c84-4505-8b24-171cd21c294d.png)

## Application area

https://app.daohaus.club/dao/0x4/0x721c1016044a7bd95332601bcbcf889f958be5b2/proposals/60

## Steps to reproduce

1. Proposals > New Proposal > Signal > Submit
2. Proposals > Proposal Card
3. Proposals > Proposal Card > Proposal Details

## What help is needed?

Change title from "Funding Proposal" to "Signal Proposal" if proposal is a signal proposal type. This change should be implemented on both the proposal card and the proposal details view.

**Comment by plor** [comment]
I waited for deploy to finish and verify it on prod. Success!
![Screenshot from 2022-04-29 15-33-14](https://user-images.githubusercontent.com/408660/166065485-1e115770-7e16-45b6-ba7c-18808c1def5e.png)
