### ISSUE TITLE
Bug: ENS not appearing for everyone

### ISSUE THREAD

**Issue by peth-eth** [odyssy-automaton/pokemol-web#1731]
Looks like ENS domains are not appearing for everyone.

For most people, setting ENS as their primary in the ENS dashboard makes their primary ENS appear instead of their hex address in DAOhaus & Yeeter.

Worked for me, but not for Griff.
He had it set from before:
![image](https://user-images.githubusercontent.com/55857222/159439113-85bae064-ad97-44c2-81a8-65ec80c5accb.png)
Yet still not appearing:
![image](https://user-images.githubusercontent.com/55857222/159439197-6677fb49-4245-40bb-a996-cee57d64225d.png)
[Link to the yeeter if anybody wants to go check it out](https://yeet.daohaus.club/dao/0x1/0x8b9280f30f386c4b8fc363d5984845d946a936c3/1)

I messaged Dekan to see if there's anything else that people need to do besides setting as primary & he told me someone else had this problem before.

Idk how rare this problem is but might be worth further investigation.

**Comment by plor** [comment]
I ran this query directly on the subgraph and was able to reproduce this for griff.eth. I don't know if there is a point before which the reverse record was set up where the event doesn't make it to this subgraph. It may be helpful to find a different subgraph that could achieve this same thing (use official ENS subgraph?) and see if this is more robust.

**Comment by brossetti1** [comment]
hey @plor @peth-yursick  I implemented a fix for this, wondering if someone can provide feedback on if this is the right solution (see changes section for details)

**Comment by plor** [comment]
Thanks @brossetti1! I'll add you to this bug and move it into testing. I can take a look, but I think @skuhlmann or @scottrepreneur will be able to comment better on the change.

**Comment by plor** [comment]
fixed by #1836 (figuring out how to link them, btw this didn't work)
