### ISSUE TITLE
Funding Proposal's 'MAX' button rounds to a number greater than treasury balance

### ISSUE THREAD

**Issue by skuhlmann** [odyssy-automaton/pokemol-web#1766]
## Expected Behavior
- WHEN a user is submitting a funding proposal 
- AND clicks 'MAX' button for funding amount 
- THEN the page should fill in the maximum amount available for funding in the treasury

## Actual Behavior
- WHEN a user is submitting a funding proposal 
- AND clicks 'MAX' button for funding amount 
- THEN the page fills in an amount greater than the treasury balance

## Application area
front end > Funding Proposals > Max button 

#### Please include a link to the page where you see the error.
https://app.daohaus.club/dao/0x64/0xb8883b8914db9c7581d49f088c23ee613e685e8c/proposals/150

  - Dao treasury: 50164.997125157737753815 
  - Proposal:        50164.99712515774

### More Details

**Step to reproduce**
1. Use a DAO with treasury that has running decimals 
2. Submit a funding proposal 
3. Select max amount
Possible solution ideas
Round to 4 decimal places AND round down instead of rounding up

**Comment by Yihwan** [comment]
hey i was perusing this repo to learn more about daohaus, and this seemed a relatively easy fix. lmk if i missed anything!

**Comment by skuhlmann** [comment]
> hey i was perusing this repo to learn more about daohaus, and this seemed a relatively easy fix. lmk if i missed anything!

Looking good! We'll test this and get back to you!

tagging this PR
https://github.com/HausDAO/daohaus-app/pull/1773

**Comment by santteegt** [comment]
Hi @Yihwan,

Thanks for your PR. While testing your changes I figured out that there was a precision issue when using JS Number primitive that would always leave dust balances on max value withdrawals, so I sent another PR with an alternative solution
