### ISSUE TITLE
Bug: Insufficient funds tooltip NaN error

### ISSUE THREAD

**Issue by skuhlmann** [odyssy-automaton/pokemol-web#1780]
- Deposit to sponsor in proposal actions
- user doesn't have enough of the deposit token
- tooltip displays NaN instead of 0

![Screenshot from 2022-04-22 10-38-30](https://user-images.githubusercontent.com/6923345/164757753-32b1ec3c-308a-43e1-951a-131c583be279.png)

**Comment by plor** [comment]
The NaN issue is fixed, but I'm still sorting out how to get the correct balance if it is non-zero.

**Comment by plor** [comment]
Ok, PR is fixed. I'm still sorting out the `useEffect` stuff, so let me know if I did something incorrectly.

**Comment by plor** [comment]
#1855 undoes this fix, need to be more careful with the solution to avoid side effects.
