### ISSUE TITLE
Bug: Incorrect 'Passed and Needs Execution' Message on proposal card

### ISSUE THREAD

**Issue by skuhlmann** [odyssy-automaton/pokemol-web#1784]
**Describe the bug**
roposal card in proposal list view displays a passed funding proposal from main treausry to minion as ‘…needs execution’ with ‘Execute’ button

**To Reproduce**

See it live [here](https://app.daohaus.club/dao/0x64/0xcd8fad1a2fc74bce90e9f5fd87164c68ecca9c12/proposals) 

1. filter ‘Funding Proposals’
2. navigate to the 2nd page

When clicked it brings up metamask with an error warning

Button is not there when clicked through to details page:
https://app.daohaus.club/dao/0x64/0xcd8fad1a2fc74bce90e9f5fd87164c68ecca9c12/proposals/248

**Expected behavior**

Display only as ‘Passed’ and remove ‘Execute’ button from list view

**Screenshots**

![Screenshot from 2022-04-25 13-28-23](https://user-images.githubusercontent.com/6923345/165160241-87f58217-d569-46d6-8b89-1530f23feb5b.png)

Where in the app is this happening?
- FrontEnd (please include route/section if possible)

`/proposals`

**Comment by jekl0x** [comment]
This was brought up by Hero DAO today and caused confusion and concern.

**Comment by plor** [comment]
Let me know if the above PR makes sense. I'm happy to discuss if there are things I missed.

**Comment by skuhlmann** [comment]
Looks good. Merging and deploying.
