### ISSUE TITLE
Bug: Disperse proposal with native token

### ISSUE THREAD

**Issue by jekl0x** [odyssy-automaton/pokemol-web#1800]
**Describe the bug**
When using the Disperse Boost to drop native xDAI coin (unwrapped) on xDai, the proposal card pulls the balance from the wrapped version.

**To Reproduce**
1. Add some xDai and wxDai into a safe minion (make sure you add less wxDAI).
2. Go to create a Disperse Proposal
3. Click on token/xDai toggle to change to native xDAI.
4. Allocate more than the total amount of wxDAI but less than the total xDAI into the array field
5. Play with the numbers to confirm.

**Expected behavior**

It should read the native xDAI balance when trying to disperse native xDAI

**Actual behavior**

It is displaying the wxDAI balance when it should be the native xDAI balance.

**Screenshots**

https://www.loom.com/share/eea5d4b522ce4ead8478e464e9b5ad43

**Comment by jekl0x** [comment]
Getting white screen when number is added in array field (didn't happen when first reported issue above).

![image](https://user-images.githubusercontent.com/102255715/168108005-a2fc6436-60fa-4c8c-97ba-da7751ede3ea.png)

https://www.loom.com/share/a34714fa65964a108a341efc08096455

**Comment by scottrepreneur** [comment]
This appears to be a larger issue. I'm not certain native token support was officially added for this as I don't see any balance handling around the inputs. Digging in here, but not a small fix it seems.

**Comment by skuhlmann** [comment]
> This appears to be a larger issue. I'm not certain native token support was officially added for this as I don't see any balance handling around the inputs. Digging in here, but not a small fix it seems.

Oh yeah that makes sense. On the vault page we make a call to the rpc or block explorer to fetch the native token balance for the minions. We'd need to replicate that somehow. It will work differently than erc20 disperse.

**Comment by santteegt** [comment]
Can you paste here the URI of the DAO that created that proposal?

**Comment by scottrepreneur** [comment]
@santteegt it's any dao. Try creating a disperse proposal on a safe minion with the native token.

**Comment by earth2travis** [comment]
@scottrepreneur this may be related to issues @santteegt reported here: https://discord.com/channels/709210493549674598/908738422666063892/985204394402410626

**Comment by santteegt** [comment]
@earth2travis that was a non-related bug I found while reproducing this issue. I'm currently doing some final tests to submit a PR

**Comment by plor** [comment]
Should I reassign this task to you @santteegt ?
