### ISSUE TITLE
Poster UX: Create New Proposal called "Configure Document Location"

### ISSUE THREAD

**Issue by plor** [odyssy-automaton/pokemol-web#1805]
Rationale: This caters to the edge case where the DAO wishes to merely change a docs location

Proposal Flow stays the same as Ratify Existing Document

- Show a proposal form with Docs selection dropdown + Docs Location field
  - WHEN proposal form is submitted
  - THEN the proposal goes for voting
  - WHEN proposal is passed
  - THEN the Markdown Document is posted to IPFS ratified
  - AND displayed at the Docs Location

Edits

- [ ] Create new Proposal
  - [ ] with name Configure Document Location
  - [ ] with description Propose & edit where Ratified documents are shown in the DAO's page

**Comment by brossetti1** [comment]
@plor id like to pick this one up but I am not sure I understand some of the context of the second checkbox - create a proposal on where documents are shown in the daos page. can you expand on that one?

I think Ive got enough for changing the Document Location, just need more detail on the second bullet point

**Comment by plor** [comment]
Testing this locally, I'm seeing a couple issues.

- Document isn't moved, a new one is added with no title and no content.

![Image](https://user-images.githubusercontent.com/408660/171723719-023d4168-5d24-48ff-b8d6-2a15e7c0faef.png)

- The proposal from the playlist is empty

![Image](https://user-images.githubusercontent.com/408660/171724060-90c2f549-da2c-4f64-b0bb-eebc6ecc3d3b.png)

- Also, it doesn't seem to work with "chain" which is what it is defaulting to for "publish and ratify"

**Comment by plor** [comment]
@brossetti1 The first bullet is fixed, second is still a problem for me.

**Comment by plor** [comment]
I'll create a separate issue for the third bullet.
