### ISSUE TITLE
Poster UX: Modify copy for Poster boost

### ISSUE THREAD

**Issue by plor** [odyssy-automaton/pokemol-web#1808]
Boost Name: Publish Boost
Boost Marketplace Copy: The Publish Boost helps your DAO create and post Markdown documents to IPFS. Once documents are published, the DAO can vote to ratify and display them in the DAO’s home and vaults page.

This is useful for providing important information to people visiting the DAO’s page, such as new member handbooks, process documents or treasury memos. Through the Poster contract, IPFS and the DAO’s voting process, the documents are published, ratified and displayed in a decentralized and trustless way.

Proposal 1: Publish New Document
- Description: Create and post a Markdown document to IPFS using the Pinata API

Proposal 2: Publish & Ratify Document
- Description: Create a Markdown document on IPFS and propose document for ratification by the DAO

Proposal 3: Ratify Existing Document
- Description: Propose an existing document for ratification by the DAO

Proposal 4: Configure Document Location
- Description: Propose & edit where Ratified documents are shown in the DAO’s page

**Comment by plor** [comment]
For context: https://hackmd.io/@arentweall/HJ8eJY8S9

**Comment by brossetti1** [comment]
@plor is this what we are looking for here?

<img width="995" alt="Screen Shot 2022-06-01 at 2 25 18 PM" src="https://user-images.githubusercontent.com/5998100/171475891-38adc0fc-b518-4c34-b963-f225a8d1530b.png">

wondering is this is what you want this to look like when you click install?

<img width="579" alt="Screen Shot 2022-06-01 at 2 24 52 PM" src="https://user-images.githubusercontent.com/5998100/171475825-1b9cf663-1911-4cf6-bfc0-3770c44dfdcf.png">

**Comment by plor** [comment]
I think the proposal 1-4 go on the next screen, asking to add the playlist.
![Screenshot from 2022-06-01 13-58-17](https://user-images.githubusercontent.com/408660/171481634-bce08e5d-6173-4e7f-a4fe-e92ae472bf64.png)

This is what it looks like currently, just changing the language there I believe.
