### ISSUE TITLE
Poster UX: Remove Markdown to Chain proposal type

### ISSUE THREAD

**Issue by plor** [odyssy-automaton/pokemol-web#1809]
Change: Remove "Post Markdown to Chain" proposal option.

Rationale: Currently, there is no meaningful difference in use case / utility for posting something to chain vs IPFS, so let’s default to posting all docs to IPFS.

**Comment by brossetti1** [comment]
im already in this one, ill just take it

**Comment by plor** [comment]
Can you reopen these PRs to point to "feature/poster-ux-updates" branch?

**Comment by plor** [comment]
![Image](https://user-images.githubusercontent.com/408660/172240003-507adb19-fb4e-4355-a81b-b0b231deaa13.png)

Realizing this task didn't totally define all places to remove the on chain posts, but I think the spirit is to remove this fully.
