### ISSUE TITLE
Allies: Deprecate backend services supporting allies feature

### ISSUE THREAD

**Issue by plor** [odyssy-automaton/pokemol-web#1814]
The last step of removing the allies feature is to take it out of the backend.
 - Remove allies from API response since it is no longer used
 - Remove lambda that updates the S3 cached data from the airtable "allies" database
 - Remove airtable "allies" database

**Comment by skuhlmann** [comment]
I've made all api and job updates. Will deploy when we deploy the new ui changes.

**Comment by skuhlmann** [comment]
#1813
