### ISSUE TITLE
Account page cann't view Deposit Token

### ISSUE THREAD

**Issue by Typto** [odyssy-automaton/pokemol-web#182]
<img width="1140" alt="111" src="https://user-images.githubusercontent.com/59275746/79062494-846b8400-7ccd-11ea-893d-30eb356fe82e.png">
Browser: Chrome
Wallet: MetaMask, WalletConnect

**Comment by dekanbro** [comment]
i think this is ok because this is for non members and they can see it in the new proposal form

**Comment by Typto** [comment]
yeah, this isn't pokemol's bug, is my bug😂

**Comment by Typto** [comment]
> i think this is ok because this is for non members and they can see it in the new proposal form

yeah, this isn't pokemol's bug, is my bug😂
