### ISSUE TITLE
Edit proposal details - placeholder property should be filled with current data - BanyanDAO

### ISSUE THREAD

**Issue by 2fd5** [odyssy-automaton/pokemol-web#1832]
**Describe the bug**
Edit proposal, name and description fields are empty

**To Reproduce**
1. Go to your DAO, proposals -> new proposal -> manage -> edit proposal details on one of the proposals
2. See that Name and Description does not have current values in the form 

**Expected behavior**

Name and description field should have the current values in the so that you can edit

**Actual behavior**

Name and description values are empty so to edit user either have to type new name or copy/paste into field then can edit

**Application area**

Where in the app is this happening?
- FrontEnd (please include route/section if possible)

**Desktop (please complete the following information):**
 - Not relevant
**Smartphone (please complete the following information):**
 - Not relevant

**Comment by brossetti1** [comment]
@2fd5 this one has been merged in, let us know if you have any follow ups
