### ISSUE TITLE
MetaPoster: deploy to additional networks

### ISSUE THREAD

**Issue by plor** [odyssy-automaton/pokemol-web#1841]
# Deploy Poster contract to supported networks

Poster is deployed on several networks, but not all of the networks DAOhaus supports. Deploy this contract to those networks and note any details necessary for further development. Coordinating with the Poster team on this would be preferred, as they may be able to offer assistance and they can reflect new deploys in their documentation.

### Chains deployed on currently

Contract address `0x000000000000cd17345801aa8147b8D3950260FF` with contracts here: https://github.com/onPoster/contract

- Mainnet Ethereum
- Ropsten
- Rinkeby
- Goerli
- Gnosis Chain

## Deliverables

- [x] Deployed to Kovan
- [ ] Deployed on IDchain
- [x] Deployed on Polygon
- [x] Deployed on Arbitrum
- [x] Deployed on Celo
- [x] Deployed on Optimism

**Comment by plor** [comment]
Remove Kovan (soon to be deprecated) and IDchain no longer supported.

**Comment by plor** [comment]
Add contract address to chain.js

**Comment by brossetti1** [comment]
I dont think we have a config for IDchain - all other deploys have gone out. having trouble verifying the contract on celo for some reason but that shouldnt block this.

**Comment by plor** [comment]
See comment above, Kovan and IDchain aren't needed.

**Comment by brossetti1** [comment]
@plor i spoke with sam on this one, deploying to the `0x000000000000cd17345801aa8147b8D3950260FF` address is not necessary, we are only using the poster for dao haus content. If anything, having our own deploy allows our subgraphs to deploy quicker since it wouldnt have to watch all the shared transactions on the shared contract

i think we should be good here

**Comment by plor** [comment]
Got it. Makes sense to me.
