### ISSUE TITLE
Bug: WXDAI is showing price to be $0

### ISSUE THREAD

**Issue by plor** [odyssy-automaton/pokemol-web#1848]
Just noticed this on Raid Guild, WXDAI is not showing any value. Not sure if this was an error in coingecko API fetch or a more persistant bug. Can be seen here: https://app.daohaus.club/dao/0x64/0xfe1084bc16427e5eb7f13fc19bcd4e641f7d571f/vaults/treasury

**Comment by brossetti1** [comment]
looks like this should be showing:



![Image](https://user-images.githubusercontent.com/5998100/170164413-0c241d10-9966-4950-8ffb-adf4bc19134f.png)

picking this one up

**Comment by brossetti1** [comment]
@plor wait i see wrapped XDAI on Raid guilds treassury, am i missing something here?


![Image](https://user-images.githubusercontent.com/5998100/170164880-082e1432-cc75-455e-aa19-2aa290345a6a.png)

**Comment by plor** [comment]
The price isn't showing up. It should be $1 per WXDAI.

**Comment by brossetti1** [comment]
doh :) i got it - thanks!

**Comment by skuhlmann** [comment]
@plor @brossetti1 

I got a fix in the indexer for this.

![Screenshot from 2022-05-25 09-00-31](https://user-images.githubusercontent.com/6923345/170294033-662547cb-94da-4daa-8570-bf524533ce90.png)

**Comment by plor** [comment]
Is this a one time thing, or do we need to document how this is done if other tokens get dropped?
