### ISSUE TITLE
Bug: Sort by DAO value not working properly

### ISSUE THREAD

**Issue by plor** [odyssy-automaton/pokemol-web#1861]
**Describe the bug**
There are several issues with sorting by value, possibly related to different chains. Further details will be added so we can document all the issues.

**To Reproduce**
1. Go to Hub -> Explore
2. Click on "Sort by Value
4. See weird sorting issues

**Expected behavior**

DAOs with highest value at top, lowest value at bottom

**Actual behavior**

DAOs not in order

**Screenshots**

Screenshots will be crowdsourced in comments.

**Additional context**
Sam thinks this is quite complex at this point, might not be worth the trouble outside of low hanging fruit.

**Comment by plor** [comment]
@oovg Created this issue if you can add context and/or screenshots

**Comment by earth2travis** [comment]
![Image](https://user-images.githubusercontent.com/522182/172947903-6ed6cc96-b30e-46a7-8b6b-11d5bc03d2d9.png)

**Comment by earth2travis** [comment]
![filters](https://user-images.githubusercontent.com/522182/172948065-047f5471-810c-47aa-a5ec-0211d63847e7.png)

**Comment by brossetti1** [comment]
@earth2travis is this still an issue? I am wondering if adding the Moloch V2.5 to these filters/sorts fixed this?

https://github.com/HausDAO/daohaus-app/pull/1912

When I sort and change around filters/sort details - then switch back to sorting by `Bank Value` it displays the daos in the correct order by bank value -- ill wait for your feedback before investigating further

heres what it looks like for me currently when i sort or mess with filters:

![Image](https://user-images.githubusercontent.com/5998100/177422895-ad6d6203-4d61-41e4-9331-1c1987a8b0ae.png)

**Comment by earth2travis** [comment]
@brossetti1 the 2.5 contracts may have been what was missing. Unfortunately, my laptop is in the shop this week and I cannot test

**Comment by earth2travis** [comment]
Please feel free to close it out if you are no longer seeing any issues

**Comment by brossetti1** [comment]
ill move it to testing and tag @plor

**Comment by plor** [comment]
I'm going to mark "can't reproduce" and if it comes up again we can try to sort it out better.
