### ISSUE TITLE
SUBGRAPH: Add new templates and factory mapping

### ISSUE THREAD

**Issue by plor** [odyssy-automaton/pokemol-web#1867]
This will need to track the new version (v1 vs v2 safe) and will be three parts.

- [x] Main subgraphs
~- [ ] Stats subgraphs~
~- [ ] Shaman subgraphs~

**Comment by skuhlmann** [comment]
rinkeby: 0x2adD83F65e6eB1015a5Cf77407EA1797CCC4E8fc

**Comment by skuhlmann** [comment]
https://github.com/HausDAO/daohaus-supergraph/commit/1e8419ce45c91e635242eb54b2f9cc81e5cdbd77

**Comment by skuhlmann** [comment]
testing with rinkeby:
https://thegraph.com/hosted-service/subgraph/odyssy-automaton/daohaus-rinkeby
