### ISSUE TITLE
Poster: Add destination to description on update proposal

### ISSUE THREAD

**Issue by plor** [odyssy-automaton/pokemol-web#1896]
# Add destination to update location proposal

The proposal to update a document location is complete, but there is no indication of where the document is currently and where it is being moved to. We should add all the relevant information to this proposal display.

<img width="1326" alt="Screen_Shot_2022-06-09_at_12 10 23_PM" src="https://user-images.githubusercontent.com/408660/172906852-fbd9ed46-82cc-4531-9ec3-73b1530a1ed4.png">

**Comment by plor** [comment]
jgreen7 from the #contributor channel showed interest in this.

**Comment by jordang7** [comment]
When trying to ratify a document
![err](https://user-images.githubusercontent.com/32372824/178109888-6ce2f359-7dc3-4f0f-8f58-2cfdf1c44424.png)
If I run the tx anyway, the error I get is 'tribute token transfer failed'

**Comment by plor** [comment]
This is coming from here: https://github.com/MolochVentures/moloch/blob/master/contracts/Moloch.sol#L198

Is it not requesting for you to approve the tribute token? I think I tested this mostly on 0 cost proposal DAOs, but that might be another bug if this proposal doesn't raise that issue.

**Comment by jordang7** [comment]
> This is coming from here: https://github.com/MolochVentures/moloch/blob/master/contracts/Moloch.sol#L198
> 
> Is it not requesting for you to approve the tribute token? I think I tested this mostly on 0 cost proposal DAOs, but that might be another bug if this proposal doesn't raise that issue.

I see. No it isn't requesting me to approve the tribute token.

**Comment by plor** [comment]
For Rinkeby I've used this token `0xdf032bc4b9dc2782bb09352007d4c57b75160b15` for WETH and the primary DAO token. I'm not sure if this is the issue or not though. On a DAO with a different token I was able to reproduce this https://rinkeby.etherscan.io/tx/0xf8e85c7acefe64ab0d6d0d131d81f4ecbcc43bf6b79ee777b6d3049aa50832a9

So it might be a testnet issue?

**Comment by plor** [comment]
If you try wrapeth.com (which is how I got the above WETH) and set up a DAO using that, can you verify that it isn't producing this issue? The DAO I was able to reproduce with was using a DAI token of unknown origins.

**Comment by jordang7** [comment]
Yeah I was able to get it working with this address `0xdf032bc4b9dc2782bb09352007d4c57b75160b15`. If I just used the preset address I had issues, but was all good with the WETH address

**Comment by plor** [comment]
Cool, let me know if you have any other issues.
