### ISSUE TITLE
Bug: Poster Documents Not Loading

### ISSUE THREAD

**Issue by plor** [odyssy-automaton/pokemol-web#1902]
**Describe the bug**
Documents posted on chain are sometimes receiving error from the subgraph. Handling this 404 with an appropriate error should be sufficient here since this doesn't happen often. But if it can be determined why the subgraph is returning the 404 in the first case, that would be a better fix.

DAO with error produced (on gnosis chain) https://app.daohaus.club/dao/0x64/0x2f102f43bbfa9da8568f5cee631c5393d4f5f74a/docs

**To Reproduce**
1. Go to link above
2. Click on one of the two documents
3. See loading text and 404 in console

**Expected behavior**

Document retrieved from subgraph (or appropriate error shown)

**Actual behavior**

No indication of problem, just seems to load forever.

**Screenshots**

When clicking the `VIEW` links from the Documents page:
![documents](https://user-images.githubusercontent.com/522182/171720171-0e7e7bd1-3558-4403-aef8-3b636aa3f4b6.png)

Both just stay in this loading state:
![Image](https://user-images.githubusercontent.com/408660/171698080-3e1d25c7-3e13-49b8-8ef8-0551edbb9135.png)

![Image](https://user-images.githubusercontent.com/408660/171698087-a7cae62a-7212-459b-850a-9e01ca12db32.png)

**Application area**

Where in the app is this happening?
- FrontEnd (docs)
- Subgraph

**Additional context**
N/A

**Comment by plor** [comment]
I'm going to move this to backlog, realized these are posted on chain (encoded) which is no longer going to be supported after our UX changes.

**Comment by plor** [comment]
Nevermind, I'm seeing the same thing with IPFS hosted document as well: https://app.daohaus.club/dao/0x64/0x046d1c324cd5ca0115e04ea1e4feecfaf44a8bf5/docs

**Comment by earth2travis** [comment]
This issue is also happening to the new document I added after the most recent updates were deployed. This document was added in Camp Fire on June 17

![Image](https://user-images.githubusercontent.com/522182/175964201-cefca2ba-e50d-44e5-92e7-256760af81c1.png)

**Comment by earth2travis** [comment]
![Image](https://user-images.githubusercontent.com/522182/175964448-cbe5a56b-a731-41ef-b06d-0186a8b9c1d0.png)

**Comment by brossetti1** [comment]
@earth2travis do you have the content of that document you added? or anyone thats failing?

this looks like to me that its failing when trying to parse the doc, the backend call is failing and i dont have access to that so its kind of hard to test without getting sam involved - trying this route first

when i try to make my own doc, it works and I can view it as well.

**Comment by earth2travis** [comment]
@brossetti1 

<img width="798" alt="overview" src="https://user-images.githubusercontent.com/522182/176250514-c2513b4d-e1a6-4ce8-8597-339e0ff6806e.png">

The one that is linked in from the Overview page as `Services` contained the followed Markdown:

```
### Synaptic Pattern Displacement

Transferring of one individual's consciousness into another

### Regeneration

Transferring healing ability to another aiding in regeneration for serious injury
```

**Comment by brossetti1** [comment]
thanks for that, I have attempted multiple ways to recreate this and cannot figure it out, I am going to be with sam on thursday, ill make sure to work with him to see why the backend is failing here.

**Comment by brossetti1** [comment]
@plor  just an update here, Sam found out that the config for poster on production was incorrect, hes updated the subgraph url, after the next deploy, this should be working.

**Comment by plor** [comment]
Cool, this one did seem like a config issue or something. Let's move this to testing until we can verify it is fixed.

**Comment by plor** [comment]
@earth2travis this fix is looking good, let me know if you see any more issues with documents. The ones above all work :)
