### ISSUE TITLE
Remove "Publish and Ratify" proposal from Publish Boost

### ISSUE THREAD

**Issue by plor** [odyssy-automaton/pokemol-web#1903]
## Remove Publish and Ratify

Discussion #1895 seems to be coming to removing this proposal type. There is a task in the backlog (#1892) for fixing it up, but for now we just want to remove it. It is up to implementation of whether to remove the code fully or just disconnect it from UI selections.

**Comment by brossetti1** [comment]
@plor i can take this one

**Comment by plor** [comment]
@brossetti1 thanks.
