### ISSUE TITLE
Replace Rivet RPC env variable

### ISSUE THREAD

**Issue by plor** [odyssy-automaton/pokemol-web#1910]
## Replace Rivet RPC

Change current env variable to take a full RPC url instead of rivet key. Any usage of this variable needs to take account of the change. Communicate the change so devs know to change their local `.env` file.

1. 
current env variable:
REACT_APP_RPC_URI

is just a rivet project id. rework this so it can be any rpc endpoint if possible.

2. Audit the other env variables to see if/where they are used and clean up the .env.sample file.

**Comment by brossetti1** [comment]
opened a pr for this one, Im open to suggestions if anyone wants to step in with something different.
