### ISSUE TITLE
Add support for Goerli network

### ISSUE THREAD

**Issue by skuhlmann** [odyssy-automaton/pokemol-web#1911]
# Overview

The graph hosted service is deprecating Kovan and Rinkeby support and recommends moving to goerli.

## Details

Here's some detail on adding a new chain:
https://hackmd.io/LkMCTZxtQKKuY2KrikQx6w

- [x] deploy all necessary contract to goerli
- [ ] update and deploy subgraphs
- [ ] update api/jobs to work with goerli
- [x] remove kovan/rinkeby from front end supported chains
- [ ] remove api/job support of rinkeby/kovan networks

I think we'll need some sort of notice crafted to announce this to the discord community. It'll give us something to point to when users come around and dont' see their kovan/rinkeby dao anymore.

**Comment by skuhlmann** [comment]
@brossetti1 

i'll jump in on the API stuff here once you have the contracts updated and subgraph pr in!

**Comment by brossetti1** [comment]
just an fyi here - Sepolia information i can find:

https://sepolia.dev
https://github.com/goerli/sepolia
https://faucet.sepolia.dev/ - faucet - get 0.05ETH every 60 minutes
https://sepolia.etherscan.io/ - block explorer

I wonder if we should also add sepolia to the config and deploys?

**Comment by brossetti1** [comment]
@skuhlmann tasks that still need to be done:

for Göerli:
- deploy 721 and 1155 subgraphs - i can do this if i have access to the graph, otherwise ill let you deploy the repos linked
    - [x] https://github.com/HausDAO/erc-1155-subgraph
    - [x] https://github.com/HausDAO/erc-721-subgraph

- double check changes and contract addresses are configured correctly 🤞🏼 

the main branch for adding goerli is https://github.com/HausDAO/daohaus-app/pull/1922
the main branch for removing rinkeby and kovan is https://github.com/HausDAO/daohaus-app/pull/1931

I have branched off all the open prs as follows:
```
master <---- deploy-goerli <----- remove-rinkeby-koven
```

**Comment by plor** [comment]
Keeping track of these for subgraph deploy.
- [x] https://thegraph.com/hosted-service/subgraph/odyssy-automaton/daohaus-goerli
- [x] https://thegraph.com/hosted-service/subgraph/odyssy-automaton/daohaus-stats-goerli
- [x] https://thegraph.com/hosted-service/subgraph/odyssy-automaton/daohaus-boosts-goerli
- [x] https://thegraph.com/hosted-service/subgraph/odyssy-automaton/daohaus-shamans-goerli
- [X] https://thegraph.com/hosted-service/subgraph/odyssy-automaton/erc1155-goerli-subgraph
- [X] https://thegraph.com/hosted-service/subgraph/odyssy-automaton/erc721-goerli-subgraph

**Comment by plor** [comment]
I changed this ticket to strictly adding Goerli support, there will be other tickets to turn off Rinkeby and Kovan. Tracked within the same milestone https://github.com/HausDAO/daohaus-app/milestone/9

**Comment by plor** [comment]
Escrow minion still needed here.

**Comment by brossetti1** [comment]
add escrow minion is here: https://github.com/HausDAO/daohaus-app/pull/1970
