### ISSUE TITLE
Bug: Voting still allowed on executed proposal

### ISSUE THREAD

**Issue by plor** [odyssy-automaton/pokemol-web#1917]
final fix - https://github.com/HausDAO/daohaus-app/pull/1948

**Describe the bug**
Minion transfer - early execution
Problem: The early execution was a success but voting is still enabled.
https://app.daohaus.club/dao/0x64/0xcd8fad1a2fc74bce90e9f5fd87164c68ecca9c12/proposals/280

**To Reproduce**
1. Submit minion proposal with early execution
2. Vote yes and execute
3. Switch to another wallet that has membership
4. See that you are still able to vote after executing

**Expected behavior**

After execution UI should no longer show the vote buttons.

**Actual behavior**

Voting is still shown after execution has been done.

**Screenshots**

![Image](https://user-images.githubusercontent.com/408660/172925157-3d5050a9-0c58-45f8-9e3c-8172adb352fd.png)

**Application area**

Where in the app is this happening?
- FrontEnd (please include route/section if possible)

**Additional context**
To reproduce you'll need to have access to two wallets on the same DAO. The first one to vote and execute, the second to see that voting is still showing.

**Comment by plor** [comment]
This works for me, though I'm having an issue with new safe minions (unrelated I think).

I did notice that the currently passing looks a bit odd with the voting buttons missing.

![Image](https://user-images.githubusercontent.com/408660/176545980-89ec525c-1c1b-4b8e-93e4-59f601f3ef57.png)

**Comment by plor** [comment]
Also, voting is still showing on the proposal list view, there are quite a few issues where the details view doesn't match the list view. Should this be created as a separate issue?

**Comment by brossetti1** [comment]
nah lets tackle it here - thanks for the thourough investigation, ill take a look

**Comment by brossetti1** [comment]
fyi this fixes this draft

![Image](https://user-images.githubusercontent.com/5998100/177013884-7b8c58d2-f4ee-423b-aae7-7e1c9a897d13.png)

**Comment by plor** [comment]
I'll just archive that draft then. Thanks.

**Comment by brossetti1** [comment]
im wondering if this fixes https://github.com/HausDAO/daohaus-app/issues/1786

**Comment by brossetti1** [comment]
linking latest pr https://github.com/HausDAO/daohaus-app/pull/1948

**Comment by plor** [comment]
#1786 is a tricky one. I'll try to reproduce again when this is merged.

**Comment by brossetti1** [comment]
this one has been deployed to https://qa.daohaus.club/ - moving into testing @plor

**Comment by plor** [comment]
Just want to note that the voting buttons are still enabled after execution on the proposal list page. This looks good on the details page though.
