### ISSUE TITLE
Bug: Quorum not met displayed incorrectly

### ISSUE THREAD

**Issue by plor** [odyssy-automaton/pokemol-web#1918]
**Describe the bug**
Minion transfer - early execution
Problem: in proposal list view, when hovering over the quorum gauge, it displays as quorum not met, but it was already executed.

**To Reproduce**
1. Create minion proposal with early execution
2. Vote and execute
3. On proposal list view, hover over quorum gauge
4. See message saying quorum not met

**Expected behavior**

Quorum gage should show that quorum is met, but not indicate execution is allowed

**Actual behavior**

Quorum gage shows incorrect message

**Screenshots**

![Image](https://user-images.githubusercontent.com/408660/172925409-65a12226-f63d-4876-a182-744d7832ae9b.png)

**Application area**

Where in the app is this happening?
- FrontEnd (/proposals)

**Additional context**
Related to other early execution issues

**Comment by plor** [comment]
Made a comment about the layout changing. Functionally this looks good though.

**Comment by brossetti1** [comment]
thanks for the testing here - i fixed this in the latest update and tested across the different quorum features:

<img width="453" alt="Screen Shot 2022-06-30 at 11 30 39 PM" src="https://user-images.githubusercontent.com/5998100/176831488-77d65773-17eb-468f-86a1-d07ae6312795.png">
