### ISSUE TITLE
Nomad: Update subgraph and UI

### ISSUE THREAD

**Issue by plor** [odyssy-automaton/pokemol-web#1924]
# Nomad safe minion

Need to update the subgraph and UI to work with safes with nomad enabled.

**Comment by plor** [comment]
Any updates to this task? Are there additional tasks that we should spawn out of this to complete the Nomad integration?

**Comment by santteegt** [comment]
I was doing some final tests on mainnet. PR is updated and ready for review

**Comment by santteegt** [comment]
Added a few more updates to my PR. Also recorded a Nomad boost demo [here](https://youtu.be/vh2aluLaO30)

**Comment by plor** [comment]
Thanks

**Comment by plor** [comment]
This was merged into the develop branch (soon to be live), but we will hide the boost for now.
