### ISSUE TITLE
Nomad: update API data

### ISSUE THREAD

**Issue by plor** [odyssy-automaton/pokemol-web#1925]
# Nomad data

Update the API to include relevant data from nomad enabled safes.

## current issues

- [x] name field from details is garbled
- [x] nomad minions not showing up in vaults list

test dao
https://app.daohaus.club/dao/0x4/0xcadac2adba361806af1231d349a85484b6011541/vaults

minion not showing in the list
0xa01c412dbfbdd0663fa81edf2d07a9018be5b829
for this dao:
0x33c5a34410ab6e35fcdd61631d6fdfc1a0dfaa48

- [ ]  change minion type to SAFE MINION V1

update mapping

**Comment by skuhlmann** [comment]
{
  minions(where: {minionAddress: "0xa01c412dbfbdd0663fa81edf2d07a9018be5b829"}) {
    id
    version
    molochAddress
    minionAddress
  }

}

**Comment by skuhlmann** [comment]
to solve #1 we'll need to start indexing goerli daos.

**Comment by plor** [comment]
Relies on #1911 for goerli.

**Comment by skuhlmann** [comment]
Subgraphs and api are updated and deployed
