### ISSUE TITLE
Turn off Rinkeby and Kovan testnets

### ISSUE THREAD

**Issue by plor** [odyssy-automaton/pokemol-web#1957]
After users have been informed of the testnets being turned off, remove these chains from the UI. Much of this work has been done and just needs to be merged in the relevant places. Review the following Pull Requests and determine if anything else needs to change.

- [x] https://github.com/HausDAO/daohaus-app/pull/1931
- [x] https://github.com/HausDAO/wrap-n-zap/pull/6
- [ ] https://github.com/HausDAO/daohaus-yeeter-v2/pull/109
- [x] https://github.com/HausDAO/daohaus-supergraph/pull/69
- [x] https://github.com/HausDAO/daohaus-stats/pull/25
- [x] https://github.com/HausDAO/daohaus-boosts/pull/5
- [x] https://github.com/HausDAO/Moloch2.5/pull/16
- [x] https://github.com/HausDAO/MinionSummonerV2/pull/27

**Comment by plor** [comment]
https://blog.ethereum.org/2022/06/21/testnet-deprecation/

**Comment by plor** [comment]
We want to hold off until September 30 to deploy this as stated in banner message.

**Comment by plor** [comment]
deploying kovan rinkeby deprecation to QA

**Comment by plor** [comment]
@skuhlmann should the other open PRs on this ticket be moved to separate tasks? How should we go about cleaning up the rest of the testnet deprecation?

**Comment by skuhlmann** [comment]
I think i've got it all cleaned up now outside of yeeter.

**Comment by plor** [comment]
thanks
