### ISSUE TITLE
Remove Rinkeby and Kovan infrastructure

### ISSUE THREAD

**Issue by plor** [odyssy-automaton/pokemol-web#1958]
After the UI has removed support for Rinkeby and Kovan, the services supporting these can be deleted.

- [x] Remove subgraphs for these networks
- [x] Turn off jobs running against DAOs on these networks

**Comment by skuhlmann** [comment]
@plor 

we can't remove the subgraphs, they'll just sit there until thegraph turns them off - but we've removed the configs from our repos.
