### ISSUE TITLE
Bug: Some NFTs break vault page (BSOD)

### ISSUE THREAD

**Issue by plor** [odyssy-automaton/pokemol-web#1962]
White screen of :stealie:  clicking into a safe minion on polygon.

https://www.loom.com/share/6ef9b52ddb2046da816cfed77bfb20f3

https://app.daohaus.club/dao/0x89/0x11ead751d5b79a37ca1c3443467a7f66b18d2b5a

https://app.daohaus.club/dao/0x89/0x11ead751d5b79a37ca1c3443467a7f66b18d2b5a/gallery

it strugglin' with one of your dao's nfts

![Image](https://user-images.githubusercontent.com/408660/177438338-17eccef4-4518-49c9-8e82-ebbf5d7a3bc0.png)

shouldn't be a tough fix

**Comment by skuhlmann** [comment]
fixed here:

https://github.com/HausDAO/daohaus-app/pull/1963
