### ISSUE TITLE
Bug: cancel minion available for non-proposer

### ISSUE THREAD

**Issue by plor** [odyssy-automaton/pokemol-web#1981]
**Describe the bug**
On the proposal list view, an unsponsored minion transaction has a cancel button that is enabled for people other than the proposer. It shows correctly when you go to the detailed view.

**To Reproduce**
1. Go to DAO and submit proposal (from minion)
2. Switch wallets to "non-proposer" address
3. See "Cancel Minion" button enabled (but fails if transaction tried)

**Expected behavior**

Non-proposer should see disabled "Cancel Minion" button (or no button at all).

**Actual behavior**

Button is enabled for non-proposer who cannot cancel.

**Screenshots**

![Image](https://user-images.githubusercontent.com/408660/181090712-d7bc7d34-4db3-4a64-81de-0fb5997e9338.png)

This is the view from the non-proposer address

**Application area**

Where in the app is this happening?
- FrontEnd (/proposals)

**Additional context**

**Comment by plor** [comment]
@jordang7 this is ready if you want to move on this, let me know if you have any questions.

**Comment by jordang7** [comment]
@plor 

Thanks, this should be easy to fix but I think I need a little clarification on who should be able to cancel the proposal before making any changes. 

So when you submit the proposal from a minion, the minion address is referenced as the `proposer`, and the account who submitted the proposal is referenced as `createdBy`. Are you saying the account who submitted the proposal should be able to see the cancel button on the detail page? 

Currently, there is conflicting logic in the codebase. I believe From the **proposal view** it's checking if the `proposal.proposer  === proposal.minionAddress`, and the **detail view** is checking  `proposal.proposer  === address`. The former will allow anyone to see the cancel button since it will always be true. The latter will only show the cancel button to the minion account.

**Comment by plor** [comment]
Yes, there is confusion on this for sure, whether the proposal is coming from the minion or whether funds are being sent to the minion is the case that is being tested there I believe. In this case `createdBy` can be used to see whether the cancel should be allowed. The address that creates the minion proposal should be able to withdraw the proposal before it is sponsored.

This task is primarily focused at the list page and not the detail page because the logic seems flipped. But on the details page, it is disabled when it should not be. Again, let me know if that should be a separate issue.

**Comment by jordang7** [comment]
I see that makes more sense now.

Yeah I believe the detail page should be a separate issue from this task in that case.

**Comment by plor** [comment]
Cool, I'll spin that out.

**Comment by plor** [comment]
@jordang7 your PR removes the button for non-proposers, but it also removes it for the address that should be able to cancel. To be clear on this, the member who proposes a proposal where a minion is doing something should be able to cancel that proposal before it is sponsored.

**Comment by jordang7** [comment]
@plor So from what I've gathered from the logic for the proposal list view, it doesn't show a cancel button for the proposer in the first place. I added an extra conditional to the `SponsorCard` component which I don't think is shown to the proposer(only non-members or members who can sponsor), so I don't believe it should be changing the view for the proposer(approve button and no cancel button at all). Do you see the cancel button as the proposer without this change? 

The component the proposer sees is the `UnlockTokenCard`, which doesn't have a cancel minion button. I can add a cancel button to that if wanted, but the issue stated no button was an excepted behavior as well so went with that. Let me know.

**Comment by plor** [comment]
Yes, it currently is working, it is just that the non-proposer can also cancel (or appears to).

![Image](https://user-images.githubusercontent.com/408660/182228245-3f862f55-48b7-44cd-ad7b-efd794c946b0.png)

(this is from the proposer's view)

**Comment by jordang7** [comment]
Ah I see. Okay I will take another look and come up with a solution.

**Comment by jordang7** [comment]
Updated PR should work for both cases now.

**Comment by jordang7** [comment]
Realized my solution was wrong again after looking it over. I believe the cancel button displayed to the proposer should be the `cancel minion` button, not the `cancel proposal. Sorry about that, let me know if I've got it right this time.

**Comment by plor** [comment]
Sorry about the delay on merging this, I had some local env issues that was delaying some testing. I did find an issue with the logic that allows both buttons to show up for some proposals (see screenshot)


![Image](https://user-images.githubusercontent.com/408660/184983642-6ec7d5f0-9c94-4bae-a839-dd0bcad5bc82.png)

**Comment by jordang7** [comment]
Hey, no problem. Could you give me the steps to recreate this issue? Tried creating a funding proposal but wasn't seeing both buttons.

**Comment by plor** [comment]
Yeah, I think it has to be to the minion address rather than the safe address. Here were the steps:

Funding proposal type
![Image](https://user-images.githubusercontent.com/408660/185696247-278f7100-0068-43ae-9ce1-03221ea64661.png)

copy the minion address (not safe)
![Image](https://user-images.githubusercontent.com/408660/185696258-da4b08b7-dd54-4062-8d36-bc1dfdd545bc.png)

If you do this is shows up in internal balance section
![Image](https://user-images.githubusercontent.com/408660/185696282-4376b5d1-5121-46bd-9aaf-188d4af2ca91.png)

paste the address in recipient
![Image](https://user-images.githubusercontent.com/408660/185696295-d4d43a6f-4f3f-4832-adaf-e9da3acea8ab.png)

See double cancels
![Image](https://user-images.githubusercontent.com/408660/185696306-378fc9b7-5bb0-4595-9c84-678ea3925d02.png)

**Comment by jordang7** [comment]
Ahh I see, thanks. Will work on this

**Comment by jordang7** [comment]
Just pushed a fix, let me know if any other issues arise

**Comment by plor** [comment]
Yeah, looks good!
