### ISSUE TITLE
Bug: Ceramic fails to connect - CORS errors

### ISSUE THREAD

**Issue by UI369** [odyssy-automaton/pokemol-web#2002]
**Describe the bug**
I tried to use the "Edit Profile" button to look at the ENS name feature.  
Navigated here: https://app.daohaus.club/dao/0x64/0xe4c6aa7bfa166af03376fe66ccbab4d8e962c064/profile/0x27773b203954fbbb3e98dfa1a85a99e1c2f40f56
And clicked "Edit Profile" button 

User facing message is: "Failed to connect please try again"  Trying again never works. 
Meanwhile, console is full of errors: 

- GEThttps://ipfs.3box.io/profile?address=0x27773b203954fbbb3e98dfa1a85a99e1c2f40f56
- [HTTP/2 404 Not Found 310ms]
- Profile does not exist [main.7507ff7b.js:2:6673484](https://app.daohaus.club/static/js/main.7507ff7b.js)
- XHROPTIONShttps://ceramic.viaheadline.xyz/api/v0/streams
- Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ceramic.viaheadline.xyz/api/v0/streams. (Reason: CORS request did not succeed). Status code: (null)

**To Reproduce**
1. Navigate to your profile page.  Example: https://app.daohaus.club/dao/0x64/0xe4c6aa7bfa166af03376fe66ccbab4d8e962c064/profile/0x27773b203954fbbb3e98dfa1a85a99e1c2f40f56

2. Click on "Edit Profile"
3. See failure message.
4. Check Console. 

**Expected behavior**
Expected to edit my profile - ideally with something about ENS name display. 

**Actual behavior**
See above. CORS errors. 

**Screenshots**

**Additional Questions**

1. [ ] Is there a security breach? 
2. [ ] Is there an issue with the smart contracts? 
3. [ ] Is there a loss of funds, shares or loot? 

**Application area**

Where in the app is this happening?
- User Profile - Frontend

**Desktop (please complete the following information):**
 - OS: Mac OS 12.4
 - Browser: Firefox
 - Version 103.0 (64-bit)

**Comment by plor** [comment]
@alexkeating it seems the headline ceramic node is acting up or we need to change something in regard to it.

**Comment by plor** [comment]
Issue should be fixed. @alexkeating figured out where this was coming from and corrected it. Please reopen and let me know if you notice this anymore. I tested and it looks good.
