### ISSUE TITLE
Bug: Moloch Token Boost not working on Goerli

### ISSUE THREAD

**Issue by plor** [odyssy-automaton/pokemol-web#2003]
**Describe the bug**
Error displayed when trying to install the Moloch Token boost on Goerli

**To Reproduce**
1. Go to DAO on Goerli > Go to boosts > Find "Moloch Token" boost
2. Click install
3. See error

**Expected behavior**

Boost is installed correctly

**Actual behavior**

Error is displayed showing javascript bug.

**Screenshots**

![Image](https://user-images.githubusercontent.com/408660/182462958-d3ca5b33-535a-4a5f-a6a8-fcdf8ba20177.png)

**Application area**

Where in the app is this happening?
- Integration or Boost

**Additional context**
Reported in #support user was trying to test this feature before switching their DAO over. I recommended testing on Rinkeby until this is resolved.

**Comment by jordang7** [comment]
It looks like the Goerli chain information is missing the `moloch_token_factory` address and that is why it's throwing the error. 

Is the MolochTokenFactory contract deployed on Goerli?

**Comment by plor** [comment]
I would guess not. We added the Goerli support after this boost was added. @scottrepreneur any considerations to take into account in deploying this?

**Comment by scottrepreneur** [comment]
Nope. Can get from the other etherscans.
1. Deploy template
2. Deploy factory
3. Verify both

**Comment by plor** [comment]
Thanks Scott!
