### ISSUE TITLE
Local Dev: SafeSDK error when running locally

### ISSUE THREAD

**Issue by plor** [odyssy-automaton/pokemol-web#2006]
My safes don't load locally and I get an error that prevents me from doing some stuff.

![Image](https://user-images.githubusercontent.com/408660/183463944-e5dc2b33-fed7-4b7e-9fca-d172d89d31cd.png)

```
ERROR getSafe Error: Invalid JSON RPC response: "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot POST [URL]</pre>\n</body>\n</html>\n"
```

**Comment by earth2travis** [comment]
This is happening on every safe. Only on Plor's local build.

**Comment by plor** [comment]
rivet change seems to require absolute url and not just API key for me. Changing env to `REACT_APP_RPC_URI=https://<API_KEY>.rpc.rivet.cloud/` fixed this.
