### ISSUE TITLE
24hr Batched email notifications

### ISSUE THREAD

**Issue by pet3r-pan** [odyssy-automaton/pokemol-web#255]
- Everyone is able to add an email to pokemol if they have DAO shares
- Every 24hrs send email of all different votes that are happening to email list

**Comment by oovg** [comment]
Is there a strong reason to limit subscription to *only members with DAO shares*? All activity that is on-chain is transparent already, so inclined to leave open to all.

An alternative method could be to allow users to add an email globally. We can auto-subscribe them to all daos they are a member of, and allow them to opt in/out of any other dao's notifications.

**Comment by oovg** [comment]
Appended sidenote: allowing all to subscribe to notifications could be attached to a 'follow' type of interaction

**Comment by pet3r-pan** [comment]
If there were an option to only allow DAO members, then yes I would choose that.

idk

**Comment by skuhlmann** [comment]
moving to airtable roadmap
