### ISSUE TITLE
Explain 'Loot' on proposal forms

### ISSUE THREAD

**Issue by skuhlmann** [odyssy-automaton/pokemol-web#265]
'I've had 5 people mess up proposals because of "Loot" and not knowing what it is. Is there any disadvantage to just changing it to "Non-Voting Shares" on the front-end and letting DAOs change the terminology as they see fit?'

'I think Loot is fun, but maybe having a little info thing that people can click or hover over to get more info/context would help?'

**Comment by oovg** [comment]
fixed
