### ISSUE TITLE
In-app notifications for DAO events

### ISSUE THREAD

**Issue by spengrah** [odyssy-automaton/pokemol-web#618]
For example...
- your membership proposal passed (you're now a member!)
- a new funding proposal voting period has started ("click here to vote")
- a new boost is now available for your DAO ("click here to set it up")

**Comment by Do-Goods** [comment]
> For example...
> 
> * your membership proposal passed (you're now a member!)
> * a new funding proposal voting period has started ("click here to vote")
> * a new boost is now available for your DAO ("click here to set it up")
Adding on here

- If your funds have been processed and are ready to withdrawal [It too me a little bit to figure out where my funds were for a proposal]

**Comment by skuhlmann** [comment]
Closing - could be a v3 feature.
