### ISSUE TITLE
[License] What is the license used for this project?

### ISSUE THREAD

**Issue by xrdavies** [odyssy-automaton/pokemol-web#853]
Hi, what is the license used for this project?

We would like to fork and reuse this project for our need, but not sure what is the license used.

**Comment by skuhlmann** [comment]
Here's the license:

https://github.com/HausDAO/pokemol-web/blob/develop/LICENSE

**Comment by xrdavies** [comment]
> Here's the license:
> 
> https://github.com/HausDAO/pokemol-web/blob/develop/LICENSE

Thank you for the information. It's GPL3
